### PR TITLE
Improve CloudWatch Agent configuration file

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request makes some improvements to the CloudWatch Agent configuration file.  It also modernizes the Ansible code by using FQCNs everywhere.

## 💭 Motivation and context ##

The CloudWatch Agent configuration file changes are the meat of this pull request, and these changes are being made for several reasons:
- To support cisagov/instance-cw-alarms-tf-module#5, which in turn supports cisagov/cool-sharedservices-freeipa#54
- To capture instance log files that were previously missing from the configuration file and hence not being forwarded to CloudWatch
- To make sure any CloudWatch Agent metrics that may be useful for debugging instance failures or improving instance performance are being sent to CloudWatch

The Ansible moderinization is just something I noticed while I was here.

This pull request also just happens to resolve cisagov/cool-system-internal#20.

## 🧪 Testing ##

I have deployed these configuration file changes to all of our staging COOL FreeIPA and OpenVPN instances and verified that they function as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Cloudtastic! ⛈️

**Review by mcdonnnj — APPROVED** [review]
This makes sense. I had one thought though: Would it make sense to define `"timezone": "UTC"` for any logs that have a `timestamp_format` field? This would ensure that regardless of the configuration of the instance the log events are in UTC.

**Comment by jsf9k** [comment]
> This makes sense. I had one thought though: Would it make sense to define `"timezone": "UTC"` for any logs that have a `timestamp_format` field? This would ensure that regardless of the configuration of the instance the log events are in UTC.

That's a good point.  I will take another pass and try to identify whether the timestamps are in local or UTC for each log.

**Comment by jsf9k** [comment]
> This makes sense. I had one thought though: Would it make sense to define `"timezone": "UTC"` for any logs that have a `timestamp_format` field? This would ensure that regardless of the configuration of the instance the log events are in UTC.

I misread your comment last night.  I think `timezone` defines the timezone to assume when parsing the timestamp from the log entry.  I think it is intended to be used in cases where the timezone to use cannot be parsed from the timestamp.  I think it does need to be added in some cases, so that is what I am doing.

**Comment by jsf9k** [comment]
> > This makes sense. I had one thought though: Would it make sense to define `"timezone": "UTC"` for any logs that have a `timestamp_format` field? This would ensure that regardless of the configuration of the instance the log events are in UTC.
> 
> I misread your comment last night. I think `timezone` defines the timezone to assume when parsing the timestamp from the log entry. I think it is intended to be used in cases where the timezone to use cannot be parsed from the timestamp. I think it does need to be added in some cases, so that is what I am doing.

By the way, all of our Linux instances are set to use UTC as local time.

**Comment by mcdonnnj** [comment]
> > This makes sense. I had one thought though: Would it make sense to define `"timezone": "UTC"` for any logs that have a `timestamp_format` field? This would ensure that regardless of the configuration of the instance the log events are in UTC.
> 
> I misread your comment last night. I think `timezone` defines the timezone to assume when parsing the timestamp from the log entry. I think it is intended to be used in cases where the timezone to use cannot be parsed from the timestamp. I think it does need to be added in some cases, so that is what I am doing.

The [configuration file documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection) reads like it's for the events logged in AWS:

> `timezone` – Optional. Specifies the time zone to use when putting timestamps on log events. The valid values are `UTC` and `Local`. The default value is `Local`.
> This parameter is ignored if you don't specify a value for `timestamp_format`.

The complete example seems to support that interpretation:

```json
{
  "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
  "log_group_name": "amazon-cloudwatch-agent.log",
  "log_stream_name": "amazon-cloudwatch-agent.log",
  "timezone": "UTC"
},
{
  "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/test.log",
  "log_group_name": "test.log",
  "log_stream_name": "test.log",
  "timezone": "Local"
}
```

I know we configure our instances to run under UTC, but since this is an independent Ansible role I thought it worth mentioning to enforce UTC in the log events regardless of how the underlying systems are configured.

**Comment by jsf9k** [comment]
> The [configuration file documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection) reads like it's for the events logged in AWS:

I don't understand how this could possibly work.  There are quite a few timestamp formats for which there is no timezone information whatsoever, so how could AWS determine what to do in those cases?  I don't see how the example supports your hypothesis; it doesn't seem to support or refute it.

**Comment by mcdonnnj** [comment]
> > The [configuration file documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection) reads like it's for the events logged in AWS:
> 
> I don't understand how this could possibly work. There are quite a few timestamp formats for which there is no timezone information whatsoever, so how could AWS determine what to do in those cases? I don't see how the example supports your hypothesis; it doesn't seem to support or refute it.

I believe I misled myself because of how poorly the AWS documentation explains the `timezone` field. Looking at the older documentation in the [AWS CloudWatch Logs user guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html#agent-configuration-file) it seems to indicate that the value of  `time_zone` (assuming it's analogous to the `timezone` field here) is used to set the timezone when one cannot be inferred from the log event's timestamp.

So in the end this is a log format specific setting and not something to blanket apply. Mea culpa.

**Comment by jsf9k** [comment]
> So in the end this is a log format specific setting and not something to blanket apply. Mea culpa.

No worries.  The documentation is not great, as you already pointed out.  I blame society.

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Pull request merged**
